---
namespace: stevefulme1
name: snowflake
version: 2.2.0
readme: README.md
authors:
  - Steve Fulmer (@stevefulme1)
description: Ansible collection for managing Snowflake data warehouse resources via the SQL REST API.
license:
  - GPL-3.0-or-later
license_file: ''
tags:
  - snowflake
  - datawarehouse
  - sql
  - governance
  - datasharing
  - cortex
  - automation
  - cloud
dependencies: {}
repository: https://github.com/stevefulme1/ansible-snowflake
documentation: https://github.com/stevefulme1/ansible-snowflake
homepage: https://github.com/stevefulme1/ansible-snowflake
issues: https://github.com/stevefulme1/ansible-snowflake/issues
build_ignore:
  - .github
  - tests
  - changelogs
  - extensions
